version: 2

sources:
  - name: raw
    description: Raw data loaded from NYC Open Data
    database: sp26dwfg
    schema: nyc_group_raw_data
    tables:
      - name: source_nyc_open_housing_maintenance_code_violations
        description: |
          NYC 311 service requests for Dept of Transportation.
          One row per service request.
        columns:
          - name: ViolationID
            description: Unique identifier of Violation
            tests:
              - unique
              - not_null
          - name: BuildingID
            description: Unique identifier of building
          - name: RegistrationID
            description: Unique identifier of valid registration information
          - name: BoroID
            description: Borough code
          - name: Borough
            description: The borough where the building is located
          - name: HouseNumber
            description: "The street number in the building's address. E.g.: the house number is '100' in '100 Gold Street'"
          - name: LowHouseNumber
            description: If there is a range for a building, the lowest house number in the building’s address.
          - name: HighHouseNumber
            description: If there is a range for a building, the highest house number in the building’s address.
          - name: StreetName
            description: "The name of the street in the building's address. E.g.: the street name is 'Gold Street' in '100 Gold Street'"
          - name: StreetCode
            description: Unique street code identifier
          - name: Postcode
            description: The postcode where the building is located
          - name: Apartment
            description: Apartment in violation, if applicable
          - name: Story
            description: Floor of violation
          - name: Block
            description: Tax block for building
          - name: Lot
            description: Tax lot for building
          - name: Class
            description: "Indicator of seriousness of the violations, where A is the least serious and C is the most serious."
          - name: InspectionDate
            description: Date when the violation was observed
          - name: ApprovedDate
            description: Date when the violation was approved
          - name: OriginalCertifyByDate
            description: Original date by which the owner was to inform HPD that the violation was corrected
          - name: OriginalCorrectByDate
            description: Original date by which the owner was to correct the violation
          - name: NewCertifyByDate
            description: If a postponement is granted, a new certify by date is established
          - name: NewCorrectByDate
            description: If a postponement is granted, a new correct by date is established
          - name: CertifiedDate
            description: Date when the violation was certified by the owner
          - name: OrderNumber
            description: Reference to the abstract description of the violation condition
          - name: NOVID
            description: Unique identifier of the Notice of Violation sent to the owner
          - name: NOVDescription
            description: Description of the violation
          - name: NOVIssuedDate
            description: Date when the NOV was sent
          - name: CurrentStatusID
            description: Unique identifier affiliated with the current violation status
          - name: CurrentStatus
            description: Current violation status
          - name: CurrentStatusDate
            description: Date when the current status went into effect
          - name: NovType
            description: Original/Reissued Notice of Violation.
          - name: ViolationStatus
            description: Status of Violation
          - name: RentImpairing
            description: A rent-impairing violation is a condition within a multiple dwelling which constitutes a fire hazard or serious threat.
          - name: Latitude
            description: Latitude coordinate of the property location.
          - name: Longitude
            description: Longitude coordinate of the property location.
          - name: CommunityBoard
            description: NYC Community District where the building is located
          - name: CouncilDistrict
            description: NYC Council District where the building is located
          - name: CensusTract
            description: Geographic area defined by the U.S. Census Bureau.
          - name: BIN
            description: Building Identification Number.
          - name: BBL
            description: Borough, Block, and Lot identifier.
          - name: NTA
            description: Neighborhood Tabulation Area.

      - name: 311_hpd_service_requests_history
        description: |
          Each row contains information about the service request, including complaint type, 
          responding agency, and geographic location.
        columns:
          - name: Unique Key
            description: Unique identifier of a Service Request (SR) in the open data set
            tests:
              - unique
              - not_null
          - name: Created Date
            description: Date SR was created
          - name: Closed Date
            description: Date SR was closed by responding agency
          - name: Agency
            description: Acronym of responding City Government Agency
          - name: Agency Name
            description: Full Agency name of responding City Government Agency
          - name: Problem
            description: Broadly describes the topic of the incident or condition.
          - name: Problem Detail
            description: Provides further detail on the incident or condition.
          - name: Additional Details
            description: A third level of detail about the complaint.
          - name: Location Type
            description: Describes the type of location used in the address information
          - name: Incident Zip
            description: Incident location zip code.
          - name: Incident Address
            description: House number of incident address.
          - name: Street Name
            description: Street name of incident address.
          - name: Status
            description: Status of SR submitted
          - name: Resolution Description
            description: Describes the last action taken on the SR by the responding agency.
          - name: Borough
            description: Provided by the submitter and confirmed by geovalidation.
          - name: Latitude
            description: Geo-based Latitude of the incident location
          - name: Longitude
            description: Geo-based Longitude of the incident location