name: 'nyc_analytics'
version: '1.0.0'
config-version: 2
# Some default settings for dbt
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

# Set up models, which are basically SQL files, to create tables
models:
 nyc_analytics:
   +materialized: table

   assignment_work:
     staging:
       +materialized: table
       +schema: nyc_transit_restaurants_staging
     
     project_staging:
       +materialized: table
       +schema: source_nyc_open_housing_maintenance_code_violations_staging
       +schema: 311_hpd_service_requests_history_staging

     marts:
       +materialized: table
       +schema: nyc_transit_restaurants_marts
       +schema: 311_hpd_complaint_marts
       +schema: open_housing_vioaltions_marts

      
       shared:
         +materialized: table

       open_restaurant_apps:
         +materialized: table

       dot_311:
         +materialized: table
         
       311_hpd_complaint:
         +materialized: table
         
       open_housing_violations:
         +materialized: table  